name: Update NuGets (Reusable)

on:
  workflow_call:
    inputs:
      root-dir:
        description: 'Katalog root do skanowania'
        required: false
        default: '.'
        type: string

jobs:
  update-nugets:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download update-nuget.ps1 with retry
        run: |
            mkdir -p tools
            for i in 1 2 3; do
            curl -fsSL https://raw.githubusercontent.com/Zonit/.github/main/tools/update-nuget.ps1 -o tools/update-nuget.ps1 && break
            echo "Download failed (attempt $i), retrying in 5s..."
            sleep 5
            done
            test -f tools/update-nuget.ps1

      - name: List tools before PowerShell
        run: ls -l tools

      - name: Run update-nuget
        shell: pwsh
        run: pwsh -File tools/update-nuget.ps1 -RootDirectory "${{ inputs.root-dir }}"

      - name: Check for changes
        id: git-check
        run: |
          if [[ -z "$(git status --porcelain)" ]]; then
            echo "No changes to commit"
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected"
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Ensure "automated-task" label exists
        if: steps.git-check.outputs.changed == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh_label_exists=$(gh api repos/${{ github.repository }}/labels/automated-task --silent 2>/dev/null || echo "404")
          if [[ "$gh_label_exists" == "404" ]]; then
            gh api repos/${{ github.repository }}/labels \
              -X POST \
              -F name='automated-task' \
              -F color='ededed' \
              -F description='PR generated by NuGet update workflow'
          fi

      - name: Prepare PR body with list of updated packages
        id: pr-body
        if: steps.git-check.outputs.changed == 'true'
        run: |
          BODY=""
          if [[ -f conditional-updates.log ]]; then
            changes=$(cat conditional-updates.log | grep -E ' -> ' | grep -vE '^\s*$')
            if [[ -n "$changes" ]]; then
              BODY="### The following NuGet packages were updated:"
              while IFS= read -r line; do
                BODY+="
          - $line"
              done <<< "$changes"
            fi
          fi

          if [[ -z "$BODY" ]]; then
              BODY="NuGet update run did not output package updates, but there are file changes."
          fi

          BODY="${BODY//'%'/'%25'}"
          echo "body<<EOF" >> $GITHUB_OUTPUT
          echo "$BODY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.git-check.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          title: "[Automated] NuGet package update"
          commit-message: "[Automated] NuGet package update"
          branch: auto/update-nuget-packages
          base: ${{ github.ref_name }}
          delete-branch: true
          labels: automated-task
          body: ${{ steps.pr-body.outputs.body }}